name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t veronikamatuk/insta:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker push
        run: docker push veronikamatuk/insta:$GITHUB_REF_NAME-$GITHUB_RUN_ID
